---
abstract: 'Validates an image and returns basic info'
author:
  - 'n0body <n0body@thisaintnews.com>'
build_requires:
  Cwd: 0
  ExtUtils::MakeMaker: 6.59
  File::Basename: 0
  Test::More: 0.94
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 1
generated_by: 'Module::Install version 1.06'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Data::Validate::Image
name: Data-Validate-Image
no_index:
  directory:
    - inc
    - t
requires:
  Image::Info: 0
  perl: 5.8.0
resources:
  bugtracker: https://github.com/n0body-/data-validate-image/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/n0body-/data-validate-image.git
version: 0.010
